import './globals.css'
import { Titillium_Web } from 'next/font/google'

const titillium = Titillium_Web({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: {
    default: 'Rakcer.ID Portal Berita Rakyat Cirebon',
    template: '%s - Rakcer.ID'
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={titillium.className + ' text-slate-700 max-w-screen-xl mx-auto h-96'}>{children}</body>
    </html>
  )
}
